version: "3.9"
networks:
  internal-network:
    driver: bridge
    internal: true
  frontend-backend:
    driver: bridge
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "backend"
    restart: "on-failure"
    ports:
      - "4000:3000"
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - ./.env
    networks:
      - internal-network
      - frontend-backend
  postgres:
    container_name: postgres
    image: "postgres:13"
    restart: on-failure
    networks:
      - internal-network
    env_file:
      - ./.env
    volumes:
      - ${PGDATA}
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: "frontend"
    restart: "on-failure"
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - frontend-backend